#!/bin/bash
# Builds the signed debug APK for Meta Quest (CI: .github/workflows/quest.yml; any Linux host with the tools below).
#   quest/tools/build-apk.sh OUT.apk
# Needs: a Swift 6.4.0 toolchain with the matching Swift SDK for Android installed (SWIFT_SDK, default
# swift-6.4.0-RELEASE_android), ANDROID_NDK_HOME (r30), ANDROID_HOME (build-tools + a platform android.jar), and the
# Khronos OpenXR loader AAR (OPENXR_AAR, quest/tools/fetch-openxr.sh). Optional: VERSION_CODE, MILESTONE.
# The Swift package is generated under build/quest-pkg: shared Sources/ (minus quest/mac-only.txt), quest/src
# (common, vk, xr, app, android), the generated HUD builder and SPIR-V, the shim modules and the C glue.
# Incremental: the package is generated into build/quest-pkg.new and synced into build/quest-pkg by content, so an
# unchanged file keeps its timestamp and SwiftPM's .build cache stays valid (tools/quest-local.sh relies on this).
# Runs on Linux (CI) and macOS (tools/quest-local.sh; SWIFT_SDKS_PATH points at its SDK directory).
set -euo pipefail
trap 'echo "build-apk.sh: failed at line $LINENO: $BASH_COMMAND"' ERR
cd "$(dirname "$0")/../.."
ROOT=$(pwd)
OUT_APK="${1:-build/blocksmith-quest.apk}"
SDK="${SWIFT_SDK:-swift-6.4.0-RELEASE_android}"
TRIPLE="${QUEST_TRIPLE:-aarch64-unknown-linux-android29}"
NDK="${ANDROID_NDK_HOME:?set ANDROID_NDK_HOME}"
export ANDROID_NDK_ROOT="$NDK" ANDROID_NDK="$NDK"      # the Swift SDK reads these; they must match the NDK it was set up with
AHOME="${ANDROID_HOME:?set ANDROID_HOME}"
AAR="${OPENXR_AAR:?set OPENXR_AAR}"
VERSION_CODE="${VERSION_CODE:-1}"
# STORE=1: the store build. Leaves out the playtest-only voice bug notes (microphone code, RECORD_AUDIO permission);
# quest/tools/storecheck.sh proves it. A head commit message containing [store] also builds and checks one in CI.
STORE="${STORE:-0}"
MILESTONE="${MILESTONE:-$(cat quest/MILESTONE 2>/dev/null || echo dev)}"
COMMIT=$(git rev-parse --short HEAD 2>/dev/null || echo unknown)
PKG=build/quest-pkg.new
BPKG=build/quest-pkg; [ "${QUEST_FAST:-0}" = 1 ] && BPKG=build/quest-pkg-fast   # own .build cache per mode
sedi() { sed "$1" "$2" > "$2.tmp" && mv "$2.tmp" "$2"; }   # in-place sed on GNU and BSD
SDKS_ARGS=(); [ -n "${SWIFT_SDKS_PATH:-}" ] && SDKS_ARGS=(--swift-sdks-path "$SWIFT_SDKS_PATH")
GEN=build/quest-gen
STAGE=build/quest-apk
rm -rf "$PKG" "$STAGE"; mkdir -p "$PKG/Sources" "$GEN" "$STAGE/lib/arm64-v8a" "$PKG/libs"

PREBUILT=$(ls -d "$NDK"/toolchains/llvm/prebuilt/* | sed -n 1p)
SYSROOT="$PREBUILT/sysroot"
export GLSLC="${GLSLC:-$(ls "$NDK"/shader-tools/*/glslc 2>/dev/null | sed -n 1p || true)}"

echo "== generated sources"
python3 quest/tools/extract_hud.py "$GEN/HudGenerated.swift"
python3 quest/tools/shaders.py "$GEN/QuestSPIRV.swift"

echo "== texture pack"
# Imported PNG textures (Resources/Textures) as assets/texpack.bin (tools/texpack.py; Android has no ImageIO).
# Regenerated when PIL is available (deterministic: unchanged PNGs give the same bytes), else the committed pack.
if [ -d Resources/Textures ] && python3 -c "import PIL" 2>/dev/null; then python3 tools/texpack.py
else echo "texpack: using the committed Resources/texpack.bin"; fi
mkdir -p "$STAGE/assets"
[ -f Resources/texpack.bin ] && cp Resources/texpack.bin "$STAGE/assets/"

echo "== package"
for m in simd os Metal; do mkdir -p "$PKG/Sources/$m"; cp quest/shims/$m/*.swift "$PKG/Sources/$m/"; done
mkdir -p "$PKG/Sources/Blocksmith"
for f in $(quest/tools/sources.sh); do cp "$f" "$PKG/Sources/Blocksmith/"; done
cp quest/src/common/*.swift quest/src/vk/*.swift quest/src/xr/*.swift quest/src/app/*.swift quest/src/android/*.swift "$PKG/Sources/Blocksmith/"
[ "$STORE" = 1 ] && rm "$PKG/Sources/Blocksmith/QuestVoiceNotes.swift"
cp "$GEN/HudGenerated.swift" "$GEN/QuestSPIRV.swift" "$PKG/Sources/Blocksmith/"
cat > "$PKG/Sources/Blocksmith/QuestBuild.swift" <<EOF
// Generated by quest/tools/build-apk.sh.
enum QuestBuild {
    static let commit = "$COMMIT"
    static let milestone = "$MILESTONE"
    static let versionCode = "$VERSION_CODE"
}
EOF
# System modules: zlib and Vulkan from the NDK sysroot, OpenXR headers from the loader AAR.
mkdir -p "$PKG/Sources/CZlib" "$PKG/Sources/CVulkan" "$PKG/Sources/COpenXR"
cp quest/c/CZlib/* "$PKG/Sources/CZlib/"
cp quest/c/CVulkan/* "$PKG/Sources/CVulkan/"
cp quest/c/COpenXR/* "$PKG/Sources/COpenXR/"
XRTMP=build/openxr-aar; rm -rf "$XRTMP"; mkdir -p "$XRTMP"; (cd "$XRTMP" && unzip -q "$ROOT/$AAR" 2>/dev/null || unzip -q "$AAR")
cp -R "$XRTMP"/prefab/modules/headers/include/openxr "$PKG/Sources/COpenXR/"
sedi 's|#include <openxr/openxr.h>|#include "openxr/openxr.h"|; s|#include <openxr/openxr_platform.h>|#include "openxr/openxr_platform.h"|' "$PKG/Sources/COpenXR/shim.h"
cp "$XRTMP"/prefab/modules/openxr_loader/libs/android.arm64-v8a/libopenxr_loader.so "$PKG/libs/"
# NativeActivity glue (C, from the NDK) + the Android headers module.
mkdir -p "$PKG/Sources/CAndroidGlue/include"
cp "$NDK"/sources/android/native_app_glue/android_native_app_glue.c "$PKG/Sources/CAndroidGlue/"
cp "$NDK"/sources/android/native_app_glue/android_native_app_glue.h "$PKG/Sources/CAndroidGlue/include/"
cp quest/c/CAndroidGlue/include/*.h "$PKG/Sources/CAndroidGlue/include/"
if [ "$STORE" != 1 ]; then
  cp quest/c/voice/voicemic.c "$PKG/Sources/CAndroidGlue/"
  cp quest/c/voice/include/voicemic.h "$PKG/Sources/CAndroidGlue/include/"
  echo '#include "voicemic.h"' >> "$PKG/Sources/CAndroidGlue/include/blocksmith_android.h"
fi

cat > "$PKG/Package.swift" <<'EOF'
// swift-tools-version:5.9
// Generated by quest/tools/build-apk.sh.
import PackageDescription
let package = Package(
    name: "BlocksmithQuest",
    products: [.library(name: "blocksmith", type: .dynamic, targets: ["Blocksmith"])],
    targets: [
        .target(name: "simd", path: "Sources/simd", swiftSettings: [.unsafeFlags(["-Ounchecked"])]),
        .target(name: "os", path: "Sources/os"),
        .target(name: "Metal", path: "Sources/Metal"),
        .systemLibrary(name: "CZlib", path: "Sources/CZlib"),
        .systemLibrary(name: "CVulkan", path: "Sources/CVulkan"),
        .systemLibrary(name: "COpenXR", path: "Sources/COpenXR"),
        .target(name: "CAndroidGlue", path: "Sources/CAndroidGlue",
                linkerSettings: [.linkedLibrary("android"), .linkedLibrary("log"), .linkedLibrary("aaudio")@VOICE_LIBS@]),
        .target(name: "Blocksmith",
                dependencies: ["simd", "os", "Metal", "CZlib", "CVulkan", "COpenXR", "CAndroidGlue"],
                path: "Sources/Blocksmith",
                swiftSettings: [.define("QUEST")@VOICE_DEFINE@, .unsafeFlags(["-Ounchecked"@WMO@, "-enforce-exclusivity=unchecked"])],
                linkerSettings: [.unsafeFlags(["-L@PKGLIBS@", "-Xlinker", "-u", "-Xlinker", "ANativeActivity_onCreate",
                                               "-Xlinker", "--no-undefined", "-Xlinker", "-z", "-Xlinker", "max-page-size=16384"])]),
    ]
)
EOF
sedi "s|@PKGLIBS@|$ROOT/$BPKG/libs|" "$PKG/Package.swift"
# QUEST_FAST=1 (tools/quest-local.sh --fast): per-file incremental -Ounchecked compile instead of one whole-module
# compile (an edit rebuilds in seconds, not minutes); less cross-file inlining, so judge frame times on a default build.
if [ "${QUEST_FAST:-0}" = 1 ]; then sedi 's|@WMO@||' "$PKG/Package.swift"; else sedi 's|@WMO@|, "-wmo"|' "$PKG/Package.swift"; fi
if [ "$STORE" = 1 ]; then sedi 's|@VOICE_LIBS@||; s|@VOICE_DEFINE@||' "$PKG/Package.swift"
else sedi 's|@VOICE_LIBS@|, .linkedLibrary("mediandk")|; s|@VOICE_DEFINE@|, .define("VOICE_NOTES")|' "$PKG/Package.swift"; fi
mkdir -p "$BPKG"; rsync -rc --delete --exclude .build "$PKG"/ "$BPKG"/

echo "== swift build ($SDK, $TRIPLE)"
# The full log goes to a file (a `head` on the pipe would SIGPIPE the build under pipefail); errors are shown below.
# QUEST_FAST: the debug configuration (the only incremental one; the target's -Ounchecked overrides its -Onone) on the
# native build system, which needs the SDK's static Foundation libraries on the link line.
FAST_ARGS=(); CONF=release
if [ "${QUEST_FAST:-0}" = 1 ]; then
  CONF=debug
  STATIC=$(find ${SWIFT_SDKS_PATH:+"$SWIFT_SDKS_PATH"} "$HOME"/.swiftpm/swift-sdks "$HOME"/.config/swiftpm/swift-sdks -type d \
    -path "*${SDK}*/swift_static-aarch64/android" -print -quit 2>/dev/null || true)
  FAST_ARGS=(--build-system native -Xlinker -L"$STATIC")
fi
(cd "$BPKG" && swift build -c $CONF ${SDKS_ARGS[@]+"${SDKS_ARGS[@]}"} ${FAST_ARGS[@]+"${FAST_ARGS[@]}"} --swift-sdk "$SDK" --triple "$TRIPLE" --static-swift-stdlib --product blocksmith \
  > "$ROOT/build/quest-swift-build.log" 2>&1) || { tail -15 build/quest-swift-build.log; echo "== compiler errors"
       sed 's/\x1b\[[0-9;]*m//g' build/quest-swift-build.log | grep -E "error:" -A3 | grep -v "Command line:\|^ *$" | head -120; exit 1; }
grep -E "Compiling|Linking|Build complete" build/quest-swift-build.log | tail -5
# (find -print -quit, not `| head -1`: head closing the pipe fails the assignment under pipefail and exits silently)
SO=$(find "$BPKG/.build" -name libblocksmith.so -ipath "*$CONF*" -print -quit || true)
echo "library: $SO"
[ -n "$SO" ] || { echo "libblocksmith.so not built"; tail -60 build/quest-swift-build.log; exit 1; }
cp "$SO" "$STAGE/lib/arm64-v8a/"
cp "$BPKG/libs/libopenxr_loader.so" "$STAGE/lib/arm64-v8a/"
cp "$SYSROOT/usr/lib/aarch64-linux-android/libc++_shared.so" "$STAGE/lib/arm64-v8a/"
READELF="$PREBUILT/bin/llvm-readelf"
# Any non-system library libblocksmith still needs (if the Swift runtime was not linked statically) comes from the SDK.
SDKDIR=$(find ${SWIFT_SDKS_PATH:+"$SWIFT_SDKS_PATH"} "$HOME"/.swiftpm/swift-sdks "$HOME"/.config/swiftpm/swift-sdks -maxdepth 1 -name "${SDK}*" -print -quit 2>/dev/null || true)
SDKDIR="${SDKDIR:-$HOME/.swiftpm/swift-sdks}"
SYSLIBS=" libc.so libm.so libdl.so liblog.so libandroid.so libvulkan.so libaaudio.so libz.so libc++_shared.so libopenxr_loader.so libEGL.so libGLESv3.so libmediandk.so "
for pass in 1 2 3; do
  for lib in "$STAGE"/lib/arm64-v8a/*.so; do
    for need in $("$READELF" -d "$lib" | sed -n 's/.*(NEEDED).*\[\(.*\)\]/\1/p'); do
      case "$SYSLIBS" in *" $need "*) continue ;; esac
      [ -f "$STAGE/lib/arm64-v8a/$need" ] && continue
      src=$(find "$SDKDIR" -name "$need" -path "*aarch64*" -print -quit 2>/dev/null || true)
      if [ -n "$src" ]; then cp "$src" "$STAGE/lib/arm64-v8a/"; echo "bundled $need"; else echo "WARNING: $need not found"; fi
    done
  done
done
"$PREBUILT/bin/llvm-strip" --strip-unneeded "$STAGE"/lib/arm64-v8a/libblocksmith.so || true
"$READELF" -d "$STAGE/lib/arm64-v8a/libblocksmith.so" | grep NEEDED
"$READELF" --dyn-syms "$STAGE/lib/arm64-v8a/libblocksmith.so" | grep -E " ANativeActivity_onCreate| android_main" || { echo "entry points missing"; exit 1; }
ls -la "$STAGE/lib/arm64-v8a/"

echo "== apk"
BT=$(ls -d "$AHOME"/build-tools/* | sort -V | tail -1)
JAR=$(ls -d "$AHOME"/platforms/android-*/android.jar | sort -V | tail -1)
sed "s/@VERSION_CODE@/$VERSION_CODE/; s/@VERSION_NAME@/0.$VERSION_CODE ($COMMIT)/" quest/android/AndroidManifest.xml > "$STAGE/AndroidManifest.xml"
[ "$STORE" = 1 ] && sedi '/RECORD_AUDIO/d' "$STAGE/AndroidManifest.xml"
"$BT/aapt2" link -o "$STAGE/base.apk" -I "$JAR" --manifest "$STAGE/AndroidManifest.xml" --min-sdk-version 29 --target-sdk-version 32 \
  -A "$STAGE/assets" -0 bin
(cd "$STAGE" && zip -q -r base.apk lib)
"$BT/zipalign" -f -P 16 4 "$STAGE/base.apk" "$STAGE/aligned.apk"
"$BT/apksigner" sign --ks quest/android/debug.keystore --ks-pass pass:android --key-pass pass:android --ks-key-alias androiddebugkey \
  --out "$OUT_APK" "$STAGE/aligned.apk"
"$BT/apksigner" verify "$OUT_APK"
ls -la "$OUT_APK"
echo "built $OUT_APK (commit $COMMIT, milestone $MILESTONE, versionCode $VERSION_CODE$( [ "$STORE" = 1 ] && echo ", store build"))"
export AAPT2="$BT/aapt2" READELF
if [ "$STORE" = 1 ]; then quest/tools/storecheck.sh "$OUT_APK"
else
  quest/tools/storecheck.sh --expect-voice "$OUT_APK"
  if [ -z "${QUEST_LOCAL:-}" ] && git log -1 --format=%B 2>/dev/null | grep -q '\[store\]'; then
    STORE_APK="$(dirname "$OUT_APK")/blocksmith-quest-store.apk"
    STORE=1 "$0" "$STORE_APK"
  fi
fi
