#!/bin/bash
# Builds the signed debug APK for Meta Quest (CI: .github/workflows/quest.yml; any Linux host with the tools below).
#   quest/tools/build-apk.sh OUT.apk
# Needs: a Swift 6.4.0 toolchain with the matching Swift SDK for Android installed (SWIFT_SDK, default
# swift-6.4.0-RELEASE_android), ANDROID_NDK_HOME (r30), ANDROID_HOME (build-tools + a platform android.jar), and the
# Khronos OpenXR loader AAR (OPENXR_AAR, quest/tools/fetch-openxr.sh). Optional: VERSION_CODE, MILESTONE.
# The Swift package is generated under build/quest-pkg: shared Sources/ (minus quest/mac-only.txt), quest/src
# (common, vk, xr, app, android), the generated HUD builder and SPIR-V, the shim modules and the C glue.
set -euo pipefail
trap 'echo "build-apk.sh: failed at line $LINENO: $BASH_COMMAND"' ERR
cd "$(dirname "$0")/../.."
ROOT=$(pwd)
OUT_APK="${1:-build/blocksmith-quest.apk}"
SDK="${SWIFT_SDK:-swift-6.4.0-RELEASE_android}"
TRIPLE="${QUEST_TRIPLE:-aarch64-unknown-linux-android29}"
NDK="${ANDROID_NDK_HOME:?set ANDROID_NDK_HOME}"
export ANDROID_NDK_ROOT="$NDK" ANDROID_NDK="$NDK"      # the Swift SDK reads these; they must match the NDK it was set up with
AHOME="${ANDROID_HOME:?set ANDROID_HOME}"
AAR="${OPENXR_AAR:?set OPENXR_AAR}"
VERSION_CODE="${VERSION_CODE:-1}"
MILESTONE="${MILESTONE:-$(cat quest/MILESTONE 2>/dev/null || echo dev)}"
COMMIT=$(git rev-parse --short HEAD 2>/dev/null || echo unknown)
PKG=build/quest-pkg
GEN=build/quest-gen
STAGE=build/quest-apk
rm -rf "$PKG" "$STAGE"; mkdir -p "$PKG/Sources" "$GEN" "$STAGE/lib/arm64-v8a" "$PKG/libs"

PREBUILT=$(ls -d "$NDK"/toolchains/llvm/prebuilt/* | sed -n 1p)
SYSROOT="$PREBUILT/sysroot"
export GLSLC="${GLSLC:-$(ls "$NDK"/shader-tools/*/glslc 2>/dev/null | sed -n 1p || true)}"

echo "== generated sources"
python3 quest/tools/extract_hud.py "$GEN/HudGenerated.swift"
python3 quest/tools/shaders.py "$GEN/QuestSPIRV.swift"

echo "== package"
for m in simd os Metal; do mkdir -p "$PKG/Sources/$m"; cp quest/shims/$m/*.swift "$PKG/Sources/$m/"; done
mkdir -p "$PKG/Sources/Blocksmith"
for f in $(quest/tools/sources.sh); do cp "$f" "$PKG/Sources/Blocksmith/"; done
cp quest/src/common/*.swift quest/src/vk/*.swift quest/src/xr/*.swift quest/src/app/*.swift quest/src/android/*.swift "$PKG/Sources/Blocksmith/"
cp "$GEN/HudGenerated.swift" "$GEN/QuestSPIRV.swift" "$PKG/Sources/Blocksmith/"
cat > "$PKG/Sources/Blocksmith/QuestBuild.swift" <<EOF
// Generated by quest/tools/build-apk.sh.
enum QuestBuild {
    static let commit = "$COMMIT"
    static let milestone = "$MILESTONE"
}
EOF
# System modules: zlib and Vulkan from the NDK sysroot, OpenXR headers from the loader AAR.
mkdir -p "$PKG/Sources/CZlib" "$PKG/Sources/CVulkan" "$PKG/Sources/COpenXR"
cp quest/c/CZlib/* "$PKG/Sources/CZlib/"
cp quest/c/CVulkan/* "$PKG/Sources/CVulkan/"
cp quest/c/COpenXR/* "$PKG/Sources/COpenXR/"
XRTMP=build/openxr-aar; rm -rf "$XRTMP"; mkdir -p "$XRTMP"; (cd "$XRTMP" && unzip -q "$ROOT/$AAR" 2>/dev/null || unzip -q "$AAR")
cp -R "$XRTMP"/prefab/modules/headers/include/openxr "$PKG/Sources/COpenXR/"
sed -i 's|#include <openxr/openxr.h>|#include "openxr/openxr.h"|; s|#include <openxr/openxr_platform.h>|#include "openxr/openxr_platform.h"|' "$PKG/Sources/COpenXR/shim.h"
cp "$XRTMP"/prefab/modules/openxr_loader/libs/android.arm64-v8a/libopenxr_loader.so "$PKG/libs/"
# NativeActivity glue (C, from the NDK) + the Android headers module.
mkdir -p "$PKG/Sources/CAndroidGlue/include"
cp "$NDK"/sources/android/native_app_glue/android_native_app_glue.c "$PKG/Sources/CAndroidGlue/"
cp "$NDK"/sources/android/native_app_glue/android_native_app_glue.h "$PKG/Sources/CAndroidGlue/include/"
cp quest/c/CAndroidGlue/include/*.h "$PKG/Sources/CAndroidGlue/include/"

cat > "$PKG/Package.swift" <<'EOF'
// swift-tools-version:5.9
// Generated by quest/tools/build-apk.sh.
import PackageDescription
let package = Package(
    name: "BlocksmithQuest",
    products: [.library(name: "blocksmith", type: .dynamic, targets: ["Blocksmith"])],
    targets: [
        .target(name: "simd", path: "Sources/simd", swiftSettings: [.unsafeFlags(["-Ounchecked"])]),
        .target(name: "os", path: "Sources/os"),
        .target(name: "Metal", path: "Sources/Metal"),
        .systemLibrary(name: "CZlib", path: "Sources/CZlib"),
        .systemLibrary(name: "CVulkan", path: "Sources/CVulkan"),
        .systemLibrary(name: "COpenXR", path: "Sources/COpenXR"),
        .target(name: "CAndroidGlue", path: "Sources/CAndroidGlue",
                linkerSettings: [.linkedLibrary("android"), .linkedLibrary("log"), .linkedLibrary("aaudio")]),
        .target(name: "Blocksmith",
                dependencies: ["simd", "os", "Metal", "CZlib", "CVulkan", "COpenXR", "CAndroidGlue"],
                path: "Sources/Blocksmith",
                swiftSettings: [.define("QUEST"), .unsafeFlags(["-Ounchecked", "-wmo", "-enforce-exclusivity=unchecked"])],
                linkerSettings: [.unsafeFlags(["-L@PKGLIBS@", "-Xlinker", "-u", "-Xlinker", "ANativeActivity_onCreate",
                                               "-Xlinker", "--no-undefined", "-Xlinker", "-z", "-Xlinker", "max-page-size=16384"])]),
    ]
)
EOF
sed -i "s|@PKGLIBS@|$ROOT/$PKG/libs|" "$PKG/Package.swift"

echo "== swift build ($SDK, $TRIPLE)"
# The full log goes to a file (a `head` on the pipe would SIGPIPE the build under pipefail); errors are shown below.
(cd "$PKG" && swift build -c release --swift-sdk "$SDK" --triple "$TRIPLE" --static-swift-stdlib --product blocksmith \
  > "$ROOT/build/quest-swift-build.log" 2>&1) || { tail -15 build/quest-swift-build.log; echo "== compiler errors"
       sed 's/\x1b\[[0-9;]*m//g' build/quest-swift-build.log | grep -E "error:" -A3 | grep -v "Command line:\|^ *$" | head -120; exit 1; }
grep -E "Compiling|Linking|Build complete" build/quest-swift-build.log | tail -5
# (find -print -quit, not `| head -1`: head closing the pipe fails the assignment under pipefail and exits silently)
SO=$(find "$PKG/.build" -name libblocksmith.so -ipath "*release*" -print -quit || true)
echo "library: $SO"
[ -n "$SO" ] || { echo "libblocksmith.so not built"; tail -60 build/quest-swift-build.log; exit 1; }
cp "$SO" "$STAGE/lib/arm64-v8a/"
cp "$PKG/libs/libopenxr_loader.so" "$STAGE/lib/arm64-v8a/"
cp "$SYSROOT/usr/lib/aarch64-linux-android/libc++_shared.so" "$STAGE/lib/arm64-v8a/"
READELF="$PREBUILT/bin/llvm-readelf"
# Any non-system library libblocksmith still needs (if the Swift runtime was not linked statically) comes from the SDK.
SDKDIR=$(find "$HOME"/.swiftpm/swift-sdks "$HOME"/.config/swiftpm/swift-sdks -maxdepth 1 -name "${SDK}*" -print -quit 2>/dev/null || true)
SDKDIR="${SDKDIR:-$HOME/.swiftpm/swift-sdks}"
SYSLIBS=" libc.so libm.so libdl.so liblog.so libandroid.so libvulkan.so libaaudio.so libz.so libc++_shared.so libopenxr_loader.so libEGL.so libGLESv3.so "
for pass in 1 2 3; do
  for lib in "$STAGE"/lib/arm64-v8a/*.so; do
    for need in $("$READELF" -d "$lib" | sed -n 's/.*(NEEDED).*\[\(.*\)\]/\1/p'); do
      case "$SYSLIBS" in *" $need "*) continue ;; esac
      [ -f "$STAGE/lib/arm64-v8a/$need" ] && continue
      src=$(find "$SDKDIR" -name "$need" -path "*aarch64*" -print -quit 2>/dev/null || true)
      if [ -n "$src" ]; then cp "$src" "$STAGE/lib/arm64-v8a/"; echo "bundled $need"; else echo "WARNING: $need not found"; fi
    done
  done
done
"$PREBUILT/bin/llvm-strip" --strip-unneeded "$STAGE"/lib/arm64-v8a/libblocksmith.so || true
"$READELF" -d "$STAGE/lib/arm64-v8a/libblocksmith.so" | grep NEEDED
"$READELF" --dyn-syms "$STAGE/lib/arm64-v8a/libblocksmith.so" | grep -E " ANativeActivity_onCreate| android_main" || { echo "entry points missing"; exit 1; }
ls -la "$STAGE/lib/arm64-v8a/"

echo "== apk"
BT=$(ls -d "$AHOME"/build-tools/* | sort -V | tail -1)
JAR=$(ls -d "$AHOME"/platforms/android-*/android.jar | sort -V | tail -1)
sed "s/@VERSION_CODE@/$VERSION_CODE/; s/@VERSION_NAME@/0.$VERSION_CODE ($COMMIT)/" quest/android/AndroidManifest.xml > "$STAGE/AndroidManifest.xml"
"$BT/aapt2" link -o "$STAGE/base.apk" -I "$JAR" --manifest "$STAGE/AndroidManifest.xml" --min-sdk-version 29 --target-sdk-version 32
(cd "$STAGE" && zip -q -r base.apk lib)
"$BT/zipalign" -f -P 16 4 "$STAGE/base.apk" "$STAGE/aligned.apk"
"$BT/apksigner" sign --ks quest/android/debug.keystore --ks-pass pass:android --key-pass pass:android --ks-key-alias androiddebugkey \
  --out "$OUT_APK" "$STAGE/aligned.apk"
"$BT/apksigner" verify "$OUT_APK"
ls -la "$OUT_APK"
echo "built $OUT_APK (commit $COMMIT, milestone $MILESTONE, versionCode $VERSION_CODE)"
