#!/usr/bin/env python3
"""Generates the Quest's copy of the Mac renderer's platform-independent parts from Sources/Renderer.swift, so the
port follows every HUD/menu change without edits to shared code:
  - the vertex/uniform structs and HudTex declared before `final class Renderer` (imports dropped),
  - the HUD/menu builder: everything from `// MARK: HUD (pixel coordinates` up to `// MARK: Headless snapshot`,
    wrapped in `extension Renderer { ... }`; its stored properties go into `final class Renderer: HudRendererBase`
    (quest/src/common/HudHost.swift provides the members it reads).
   quest/tools/extract_hud.py OUT.swift"""
import os, sys
here = os.path.dirname(os.path.abspath(__file__))
src = open(os.path.join(here, '..', '..', 'Sources', 'Renderer.swift')).read().split('\n')
out = sys.argv[1]
cls = next(i for i, l in enumerate(src) if l.startswith('final class Renderer'))
head = [l for l in src[:cls] if not l.startswith('import ')]
a = next(i for i, l in enumerate(src) if l.strip().startswith('// MARK: HUD (pixel coordinates'))
b = next(i for i, l in enumerate(src) if l.strip().startswith('// MARK: Headless snapshot'))
body = src[a:b]
# Stored properties at member level (4-space indent, `var x: T = v` / `let x = v`, not computed) move into the class.
import re
stored, rest = [], []
for l in body:
    if re.match(r'^    (private )?(var|let) \w+(: [^={]+)? = [^{]*$', l): stored.append(l)
    else: rest.append(l)
gen = ['// Generated by quest/tools/extract_hud.py from Sources/Renderer.swift: do not edit.',
       'import Foundation', 'import simd', ''] + head + \
      ['', '// The HUD host (members the builder reads live in HudRendererBase, quest/src/common/HudHost.swift).',
       'final class Renderer: HudRendererBase {'] + stored + ['}', '', 'extension Renderer {'] + rest + ['}', '']
os.makedirs(os.path.dirname(os.path.abspath(out)), exist_ok=True)
open(out, 'w').write('\n'.join(gen))
print(f'extract_hud.py: {len(head)} header lines + HUD lines {a + 1}-{b} -> {out}')
