#!/usr/bin/env python3
"""Compiles quest/shaders/*.vert|*.frag to SPIR-V (glslc from the NDK, or glslangValidator) and writes a Swift file
with each module as a base64 string: QuestSPIRV.words("chunk.vert") -> [UInt32].
   quest/tools/shaders.py OUT.swift"""
import base64, os, re, shutil, subprocess, sys, tempfile

here = os.path.dirname(os.path.abspath(__file__))
src = os.path.join(here, '..', 'shaders')
out = sys.argv[1]
common = open(os.path.join(src, 'common.glsl')).read()
glslc = os.environ.get('GLSLC') or shutil.which('glslc')
validator = shutil.which('glslangValidator')
mods = {}
tmp = tempfile.mkdtemp()
for name in sorted(os.listdir(src)):
    if not (name.endswith('.vert') or name.endswith('.frag')):
        continue
    text = open(os.path.join(src, name)).read().replace('#include "common.glsl"', common)
    stage = 'vert' if name.endswith('.vert') else 'frag'
    path = os.path.join(tmp, name)
    open(path, 'w').write(text)
    spv = path + '.spv'
    if glslc:
        cmd = [glslc, '--target-env=vulkan1.1', '-O', f'-fshader-stage={stage}', path, '-o', spv]
    elif validator:
        cmd = [validator, '-V', '--target-env', 'vulkan1.1', '-S', stage, path, '-o', spv]
    else:
        sys.exit('shaders.py: no glslc or glslangValidator')
    r = subprocess.run(cmd, capture_output=True, text=True)
    if r.returncode != 0:
        sys.exit(f'shaders.py: {name} failed:\n{r.stdout}{r.stderr}')
    mods[name] = base64.b64encode(open(spv, 'rb').read()).decode()
lines = ['// Generated by quest/tools/shaders.py from quest/shaders: do not edit.', 'import Foundation', '',
         'enum QuestSPIRV {', '    static let modules: [String: String] = [']
for k, v in mods.items():
    lines.append(f'        "{k}": "{v}",')
lines += ['    ]', '    static func words(_ name: String) -> [UInt32] {',
          '        guard let b64 = modules[name], let d = Data(base64Encoded: b64) else { fatalError("missing shader \\(name)") }',
          '        return d.withUnsafeBytes { Array($0.bindMemory(to: UInt32.self)) }', '    }', '}', '']
os.makedirs(os.path.dirname(os.path.abspath(out)), exist_ok=True)
open(out, 'w').write('\n'.join(lines))
print(f'shaders.py: {len(mods)} modules -> {out}')
