class_name CharacterFactory
extends RefCounted
## Spawns Frontier humans generated by the character pipeline (frontier/tools/characters, see design/CHARACTERS.md).
##
## API (all static):
##   CharacterFactory.spawn(seed: int, role := "", opts := {}) -> FrontierCharacter
##       Deterministic: the same seed (+ role) always gives the same person, outfit colours and voice-free face.
##       role filters the catalogue by tag: "townsman", "townswoman", "rancher", "worker", "gentleman", "lady",
##       "elder", "drifter", "hero" ... ("" = anyone except the protagonist). opts: {"no_hat": true, "lod": "npc"}
##   CharacterFactory.spawn_id(id: String, opts := {}) -> FrontierCharacter   e.g. spawn_id("ruth_caddell")
##   CharacterFactory.catalog() -> Dictionary          parsed characters.json (ids, roles, tags, tris, files)
##   CharacterFactory.animation_library() -> AnimationLibrary   shared clips (names in design/CHARACTERS.md)
##   CharacterFactory.clip_info(name) -> Dictionary     {"loop", "speed" (m/s), "duration", "contacts": {...}}
##   CharacterFactory.available() -> bool               false when the generated assets are not present
## The returned FrontierCharacter (character.gd) has play()/seek(), set_viseme(), set_expression(), blink(),
## look_at_point(), head_position(); its Skeleton3D uses Godot's SkeletonProfileHumanoid bone names.
##
## Assets are searched in res://assets/ext/characters (CI release characters.zip, fetched by tools/fetch_assets.sh)
## then res://assets/characters_out (local generator output). Imported .glb files are used when the editor has
## imported them; otherwise they are parsed at runtime with GLTFDocument.

const SEARCH_DIRS := ["res://assets/ext/characters", "res://assets/characters_out"]
const ANIM_LIB_NAME := "lib"

static var _dir := ""
static var _catalog: Dictionary = {}
static var _scenes: Dictionary = {}        # id -> PackedScene (runtime-built cache)
static var _anim_lib: AnimationLibrary
static var _clips: Dictionary = {}
static var _materials: CharacterMaterials
static var _mutex := Mutex.new()
static var _warming := false
static var _warm_group := -1
static var _warm_anim := -1


## Wait for the warm-up and drop every cached resource before the engine tears down (static Resource caches that
## outlive the script server abort the process at exit).
static func shutdown() -> void:
	if _warm_group >= 0:
		WorkerThreadPool.wait_for_task_completion(_warm_group)
		_warm_group = -1
	if _warm_anim >= 0:
		WorkerThreadPool.wait_for_task_completion(_warm_anim)
		_warm_anim = -1
	_scenes.clear()
	_anim_lib = null
	_materials = null
	FrontierCharacter.clear_static()


## Loads and prepares every character scene and the animation library on worker threads, so spawning someone in the
## middle of a ride never parses a glTF on the main thread. Until a look is ready, spawn() picks a ready one.
static func warm_up() -> void:
	if _warming or not available():
		return
	_warming = true
	# a role-diverse subset sized by quality preset (every look resident at once costs GPU memory an 8 GB Mac and a
	# Quest can't spare); spawns pick among prepared looks, so a town still reads varied
	var budget := int({"low": 8, "medium": 12, "high": 16, "ultra": 24, "quest": 6, "preview": 10}.get(Game.quality_name, 12))
	var todo: Array = []
	var by_role := {}
	for c in catalog().get("characters", []):
		var tags: Array = c.get("tags", [])
		if tags.has("hero"):
			if str(c["id"]) == "ruth_caddell":
				todo.append(str(c["id"]))
			continue
		var r := str(c.get("role", ""))
		if not by_role.has(r):
			by_role[r] = []
		by_role[r].append(str(c["id"]))
	var round := 0
	while todo.size() < budget:
		var added := false
		for r in by_role.keys():
			if round < by_role[r].size() and todo.size() < budget:
				todo.append(by_role[r][round])
				added = true
		if not added:
			break
		round += 1
	_warm_anim = WorkerThreadPool.add_task(func(): animation_library(), false, "character anims")
	# one look at a time on one worker: parallel glTF builds pushed every look's texture uploads into the first
	# frames at once (CI's paravirtual GPU timed out on that frame) and starved world streaming of cores
	_warm_group = WorkerThreadPool.add_task(func():
		var t0 := Time.get_ticks_msec()
		for id in todo:
			if _is_ready(id):
				continue
			var ps := _build_scene(id, _info(id))
			if ps:
				_mutex.lock()
				_scenes[id] = ps
				_mutex.unlock()
		print("characters: %d looks ready in %d ms" % [todo.size(), Time.get_ticks_msec() - t0]), false, "character scenes")


static func _is_ready(id: String) -> bool:
	_mutex.lock()
	var r := _scenes.has(id)
	_mutex.unlock()
	return r


static func available() -> bool:
	if Game.disabled("characters"):
		return false
	return not catalog().is_empty()


static func asset_dir() -> String:
	if _dir == "":
		for d in SEARCH_DIRS:
			if FileAccess.file_exists(d.path_join("characters.json")):
				_dir = d
				break
	return _dir


static func catalog() -> Dictionary:
	if _catalog.is_empty() and asset_dir() != "":
		var txt := FileAccess.get_file_as_string(asset_dir().path_join("characters.json"))
		var parsed = JSON.parse_string(txt)
		if parsed is Dictionary:
			_catalog = parsed
			var ap := asset_dir().path_join("animations.json")
			if FileAccess.file_exists(ap):
				var an = JSON.parse_string(FileAccess.get_file_as_string(ap))
				if an is Dictionary:
					_catalog["animations"] = an
			for c in _catalog.get("animations", {}).get("clips", []):
				_clips[c["name"]] = c
	return _catalog


static func ids(role := "") -> PackedStringArray:
	var out := PackedStringArray()
	for c in catalog().get("characters", []):
		var tags: Array = c.get("tags", [])
		if role == "":
			if not tags.has("hero"):
				out.append(c["id"])
		elif tags.has(role) or c.get("role", "") == role:
			out.append(c["id"])
	return out


static func spawn(seed: int, role := "", opts := {}) -> FrontierCharacter:
	var pool := ids(role)
	if pool.is_empty():
		pool = ids("")
	if pool.is_empty():
		push_warning("CharacterFactory: no generated characters found (run tools/characters/run.sh or fetch_assets.sh)")
		return null
	if _warming:
		# prefer looks already prepared off-thread; any ready look beats a main-thread glTF parse mid-game
		var ready := Array(pool).filter(_is_ready)
		if ready.is_empty():
			ready = Array(ids("")).filter(_is_ready)
		if not ready.is_empty():
			pool = PackedStringArray(ready)
	var h := hash(str(seed) + ":" + role)
	var id := pool[posmod(h, pool.size())]
	var o := opts.duplicate()
	o["variant_seed"] = seed
	return spawn_id(id, o)


static func spawn_id(id: String, opts := {}) -> FrontierCharacter:
	var info := _info(id)
	if info.is_empty():
		push_warning("CharacterFactory: unknown character " + id)
		return null
	var scene := _scene(id, info)
	if scene == null:
		return null
	var model: Node3D = scene.instantiate()
	model.name = "Model"
	var ch := FrontierCharacter.new()
	ch.name = id
	ch.character_id = id
	ch.info = info
	ch.add_child(model)
	if _materials == null:
		_materials = CharacterMaterials.new()
	var rng := RandomNumberGenerator.new()
	rng.seed = hash(id + ":" + str(opts.get("variant_seed", 0)))
	_materials.apply(model, info, rng, opts)
	ch.setup(model, animation_library(), opts)
	return ch


static func animation_library() -> AnimationLibrary:
	_mutex.lock()
	var have := _anim_lib != null
	_mutex.unlock()
	if have:
		return _anim_lib
	var lib := _load_anim_library()
	_mutex.lock()
	if _anim_lib == null:
		_anim_lib = lib
	_mutex.unlock()
	return _anim_lib


static func _load_anim_library() -> AnimationLibrary:
	var out: AnimationLibrary = null
	if asset_dir() != "":
		var file := str(catalog().get("animations", {}).get("file", "animations.glb"))
		var path := asset_dir().path_join(file)
		var root := _load_glb(path)
		if root == null:
			return null
		var ap := _find_anim_player(root)
		out = AnimationLibrary.new()
		if ap:
			for lib_name in ap.get_animation_library_list():
				var lib := ap.get_animation_library(lib_name)
				for anim_name in lib.get_animation_list():
					var a: Animation = lib.get_animation(anim_name).duplicate(true)
					_normalise_tracks(a)
					var info: Dictionary = _clips.get(anim_name, {})
					a.loop_mode = Animation.LOOP_LINEAR if info.get("loop", false) else Animation.LOOP_NONE
					out.add_animation(anim_name, a)
		root.free()
	return out


static func clip_info(clip: String) -> Dictionary:
	catalog()
	return _clips.get(clip, {})


# --- internals -----------------------------------------------------------------------------------------------------
static func _info(id: String) -> Dictionary:
	for c in catalog().get("characters", []):
		if c["id"] == id:
			return c
	return {}


static func _scene(id: String, info: Dictionary) -> PackedScene:
	_mutex.lock()
	var cached: PackedScene = _scenes.get(id)
	_mutex.unlock()
	if cached:
		return cached
	var ps := _build_scene(id, info)
	if ps:
		_mutex.lock()
		_scenes[id] = ps
		_mutex.unlock()
	return ps


static func _build_scene(id: String, info: Dictionary) -> PackedScene:
	var path := asset_dir().path_join(str(info.get("file", id + ".glb")))
	var root := _load_glb(path)
	if root == null:
		push_warning("CharacterFactory: cannot load " + path)
		return null
	var ap := _find_anim_player(root)
	if ap:
		ap.get_parent().remove_child(ap)
		ap.free()
	var ps := PackedScene.new()
	_set_owner(root, root)
	ps.pack(root)
	root.free()
	return ps


static func _load_glb(path: String) -> Node:
	if ResourceLoader.exists(path):
		var res = load(path)
		if res is PackedScene:
			return res.instantiate()
	if not FileAccess.file_exists(path):
		return null
	var doc := GLTFDocument.new()
	var state := GLTFState.new()
	if doc.append_from_file(path, state) != OK:
		return null
	return doc.generate_scene(state)


static func _set_owner(n: Node, owner: Node) -> void:
	for c in n.get_children():
		c.owner = owner
		_set_owner(c, owner)


static func _find_anim_player(n: Node) -> AnimationPlayer:
	if n is AnimationPlayer:
		return n
	for c in n.get_children():
		var r := _find_anim_player(c)
		if r:
			return r
	return null


static func _normalise_tracks(a: Animation) -> void:
	## Point every track at "Skeleton:<bone>"; FrontierCharacter renames its Skeleton3D to "Skeleton" and roots the
	## AnimationPlayer at the skeleton's parent, so one library drives every character.
	for t in a.get_track_count():
		var p := a.track_get_path(t)
		if p.get_subname_count() == 0:
			continue
		a.track_set_path(t, NodePath("Skeleton:" + p.get_concatenated_subnames()))
