"""Core MakeHuman/MPFB2 operations for the Frontier character builder (runs inside the `bpy` module).

Everything here is deterministic for a given spec: no randomness lives in this file (see appearance.py).
"""
import os
import gzip
import glob
import hashlib
import numpy as np
import bpy
import bmesh
from mathutils import Vector, Matrix

import mhenv

# --- Skeleton -----------------------------------------------------------------------------------------------------
# MPFB "game_engine" rig -> Godot SkeletonProfileHumanoid bone names. The game rig is exactly Godot's humanoid
# profile (minus Jaw), so BoneMap retargeting is the identity and every animation library shares these names.
GODOT_BONES = {
    "Root": "Root", "pelvis": "Hips", "spine_01": "Spine", "spine_02": "Chest", "spine_03": "UpperChest",
    "neck_01": "Neck", "head": "Head",
}
for side, S in (("l", "Left"), ("r", "Right")):
    GODOT_BONES.update({
        "clavicle_" + side: S + "Shoulder", "upperarm_" + side: S + "UpperArm", "lowerarm_" + side: S + "LowerArm",
        "hand_" + side: S + "Hand",
        "thumb_01_" + side: S + "ThumbMetacarpal", "thumb_02_" + side: S + "ThumbProximal",
        "thumb_03_" + side: S + "ThumbDistal",
        "thigh_" + side: S + "UpperLeg", "calf_" + side: S + "LowerLeg", "foot_" + side: S + "Foot",
        "ball_" + side: S + "Toes",
    })
    for mh, gd in (("index", "Index"), ("middle", "Middle"), ("ring", "Ring"), ("pinky", "Little")):
        GODOT_BONES["%s_01_%s" % (mh, side)] = S + gd + "Proximal"
        GODOT_BONES["%s_02_%s" % (mh, side)] = S + gd + "Intermediate"
        GODOT_BONES["%s_03_%s" % (mh, side)] = S + gd + "Distal"

# --- Face blend shapes ---------------------------------------------------------------------------------------------
# name -> [(target, weight)]. Targets: ARKit face units (extra-targets/faceunits01) and Meta visemes (visemes02),
# both CC0 MakeHuman community targets. Godot API aliases live in src/actors/character_factory.gd.
FACE_SHAPES = {
    "blink_L": [("eyeBlinkLeft", 1.0)], "blink_R": [("eyeBlinkRight", 1.0)],
    "squint_L": [("eyeSquintLeft", 1.2), ("cheekSquintLeft", 0.5)],
    "squint_R": [("eyeSquintRight", 1.2), ("cheekSquintRight", 0.5)],
    "wide_L": [("eyeWideLeft", 1.0)], "wide_R": [("eyeWideRight", 1.0)],
    "brow_raise": [("browInnerUp", 0.9), ("browOuterUpLeft", 1.5), ("browOuterUpRight", 1.5)],
    "brow_inner_up": [("browInnerUp", 1.4)],
    "brow_furrow": [("browDownLeft", 1.4), ("browDownRight", 1.4)],
    "jaw_open": [("jawOpen", 1.0)],
    # the autogenerated units are subtle: expressions are boosted so weight 1.0 reads at dialogue distance
    "smile_L": [("mouthSmileLeft", 1.3), ("cheekSquintLeft", 0.6), ("mouthStretchLeft", 0.1)],
    "smile_R": [("mouthSmileRight", 1.3), ("cheekSquintRight", 0.6), ("mouthStretchRight", 0.1)],
    "frown": [("mouthFrownLeft", 1.5), ("mouthFrownRight", 1.5), ("mouthShrugLower", 0.5)],
    "sneer_L": [("noseSneerLeft", 1.4), ("mouthUpperUpLeft", 0.7)],
    "sneer_R": [("noseSneerRight", 1.4), ("mouthUpperUpRight", 0.7)],
    "pucker": [("mouthPucker", 1.0)], "funnel": [("mouthFunnel", 1.0)],
    "press": [("mouthPressLeft", 1.0), ("mouthPressRight", 1.0)],
    "cheek_puff": [("cheekPuff", 1.0)],
}
for v in ("sil", "PP", "FF", "TH", "DD", "kk", "CH", "SS", "nn", "RR", "aa", "E", "I", "O", "U"):
    FACE_SHAPES["vis_" + v] = [("viseme_" + v, 1.0)]

HEAD_PARTS = ("eyebrows", "eyelashes", "teeth", "tongue", "eyes", "beard")


def reset_scene():
    bpy.ops.wm.read_factory_settings(use_empty=True)
    mhenv._enabled = False
    mhenv.enable_mpfb()


# --- Targets -------------------------------------------------------------------------------------------------------
_TARGET_INDEX = None


def target_path(name):
    """Resolve a target name (without extension) in MPFB's bundled targets or the extra-targets packs."""
    global _TARGET_INDEX
    if _TARGET_INDEX is None:
        _TARGET_INDEX = {}
        for root in (os.path.join(mhenv.MPFB_DATA, "targets"), os.path.join(mhenv.MH_EXTRA, "assets")):
            for p in glob.glob(os.path.join(root, "**", "*.target*"), recursive=True):
                b = os.path.basename(p).replace(".gz", "").replace(".target", "")
                _TARGET_INDEX.setdefault(b, p)
    return _TARGET_INDEX.get(name)


_TARGET_CACHE = {}


def read_target(name, scale=0.1):
    """-> (indices int array, deltas float32 Nx3 in Blender space, metres)."""
    if name in _TARGET_CACHE:
        return _TARGET_CACHE[name]
    p = target_path(name)
    if p is None:
        raise IOError("target not found: " + name)
    op = gzip.open if p.endswith(".gz") else open
    idx, d = [], []
    with op(p, "rt") as f:
        for line in f:
            s = line.strip()
            if not s or s[0] in "#\"":
                continue
            a = s.split()
            idx.append(int(a[0]))
            d.append((float(a[1]), -float(a[3]), float(a[2])))
    r = (np.array(idx, dtype=np.int64), np.array(d, dtype=np.float32).reshape(-1, 3) * scale)
    _TARGET_CACHE[name] = r
    return r


def combined_delta(nverts, parts):
    out = np.zeros((nverts, 3), dtype=np.float32)
    for name, w in parts:
        i, d = read_target(name)
        m = i < nverts
        np.add.at(out, i[m], d[m] * w)
    return out


# --- Mesh helpers --------------------------------------------------------------------------------------------------
def get_co(obj, key=None):
    n = len(obj.data.vertices)
    a = np.empty(n * 3, dtype=np.float32)
    if key is None:
        obj.data.vertices.foreach_get("co", a)
    else:
        key.data.foreach_get("co", a)
    return a.reshape(n, 3)


def set_co(obj, co, key=None):
    if key is None:
        obj.data.vertices.foreach_set("co", co.astype(np.float32).ravel())
        obj.data.update()
    else:
        key.data.foreach_set("co", co.astype(np.float32).ravel())


def ensure_basis(obj):
    if obj.data.shape_keys is None:
        obj.shape_key_add(name="Basis", from_mix=False)


def add_shape(obj, name, co):
    ensure_basis(obj)
    k = obj.shape_key_add(name=name, from_mix=False)
    set_co(obj, co, k)
    k.value = 0.0
    return k


def group_vertex_mask(obj, group_name, threshold=0.0):
    """Boolean mask of vertices in a vertex group (weight > threshold)."""
    n = len(obj.data.vertices)
    m = np.zeros(n, dtype=bool)
    vg = obj.vertex_groups.get(group_name)
    if vg is None:
        return m
    gi = vg.index
    for v in obj.data.vertices:
        for g in v.groups:
            if g.group == gi and g.weight > threshold:
                m[v.index] = True
                break
    return m


def delete_vertices(obj, mask):
    """Delete masked vertices (keeps shape keys and attributes consistent)."""
    if not mask.any():
        return
    me = obj.data
    bm = bmesh.new()
    bm.from_mesh(me)
    bm.verts.ensure_lookup_table()
    bmesh.ops.delete(bm, geom=[bm.verts[i] for i in np.nonzero(mask)[0]], context="VERTS")
    bm.to_mesh(me)
    bm.free()
    me.update()


def mhclo_arrays(mhclo, nproxy):
    vi = np.zeros((nproxy, 3), dtype=np.int64)
    vw = np.zeros((nproxy, 3), dtype=np.float32)
    for i in range(nproxy):
        info = mhclo.verts.get(i)
        if info is None:
            continue
        vi[i] = info["verts"]
        vw[i] = info["weights"]
    return vi, vw


def transfer_delta(vi, vw, delta):
    d = np.zeros((vi.shape[0], 3), dtype=np.float32)
    ok = vi.max(axis=1) < delta.shape[0]
    for k in range(3):
        d[ok] += vw[ok, k:k + 1] * delta[vi[ok, k]]
    return d


# --- Images / materials --------------------------------------------------------------------------------------------
def cache_dir():
    d = os.path.join(mhenv.FRONTIER, "build", "charcache", "tex")
    os.makedirs(d, exist_ok=True)
    return d


def resized_image(path, size, fmt=None, mode=None):
    """Load an image file resized to `size` (longest side) through a disk cache; returns bpy image."""
    from PIL import Image
    st = os.stat(path)
    h = hashlib.sha1(("%s|%d|%d|%s|%s" % (path, st.st_size, size, fmt, mode)).encode()).hexdigest()[:16]
    im = Image.open(path)
    has_alpha = im.mode in ("RGBA", "LA") or "transparency" in im.info
    ext = fmt or ("png" if has_alpha else "jpg")
    out = os.path.join(cache_dir(), "%s_%s.%s" % (os.path.splitext(os.path.basename(path))[0], h, ext))
    if not os.path.exists(out):
        if mode:
            im = im.convert(mode)
        elif ext == "jpg":
            im = im.convert("RGB")
        elif im.mode not in ("RGB", "RGBA"):
            im = im.convert("RGBA" if has_alpha else "RGB")
        if max(im.size) > size:
            im = im.resize((size, size * im.size[1] // im.size[0]), Image.LANCZOS)
        if ext == "jpg":
            im.save(out, quality=92)
        else:
            im.save(out, optimize=True)
    img = bpy.data.images.load(out, check_existing=True)
    return img


def parse_mhmat(path):
    d = {}
    base = os.path.dirname(path)
    with open(path, encoding="utf-8", errors="replace") as f:
        for line in f:
            s = line.strip()
            if not s or s.startswith("#"):
                continue
            k, _, v = s.partition(" ")
            d[k] = v.strip()
    for k in ("diffuseTexture", "normalmapTexture", "aomapTexture", "specularmapTexture", "bumpmapTexture"):
        if k in d:
            p = d[k]
            cands = [os.path.join(base, p), os.path.join(base, os.path.basename(p)),
                     os.path.join(mhenv.MH_ASSETS, p)]
            d[k] = next((c for c in cands if os.path.exists(c)), None)
    return d


def make_material(name, albedo=None, normal=None, ao=None, color=(0.8, 0.8, 0.8, 1.0), roughness=0.6,
                  alpha=False, alpha_clip=False, size=1024, metallic=0.0):
    """Principled material that the glTF exporter maps 1:1 (baseColor/normal/occlusion)."""
    mat = bpy.data.materials.new(name)
    mat.use_nodes = True
    nt = mat.node_tree
    nt.nodes.clear()
    out = nt.nodes.new("ShaderNodeOutputMaterial")
    bsdf = nt.nodes.new("ShaderNodeBsdfPrincipled")
    nt.links.new(bsdf.outputs[0], out.inputs[0])
    bsdf.inputs["Base Color"].default_value = color
    bsdf.inputs["Roughness"].default_value = roughness
    bsdf.inputs["Metallic"].default_value = metallic
    if albedo:
        t = nt.nodes.new("ShaderNodeTexImage")
        t.image = resized_image(albedo, size)
        nt.links.new(t.outputs["Color"], bsdf.inputs["Base Color"])
        if alpha:
            nt.links.new(t.outputs["Alpha"], bsdf.inputs["Alpha"])
    if normal:
        t = nt.nodes.new("ShaderNodeTexImage")
        t.image = resized_image(normal, size, fmt="png", mode="RGB")
        t.image.colorspace_settings.name = "Non-Color"
        nm = nt.nodes.new("ShaderNodeNormalMap")
        nt.links.new(t.outputs["Color"], nm.inputs["Color"])
        nt.links.new(nm.outputs["Normal"], bsdf.inputs["Normal"])
    if ao:
        # glTF occlusion via the exporter's "glTF Material Output" group.
        grp = _gltf_output_group()
        g = nt.nodes.new("ShaderNodeGroup")
        g.node_tree = grp
        t = nt.nodes.new("ShaderNodeTexImage")
        t.image = resized_image(ao, size // 2, fmt="jpg", mode="L")
        t.image.colorspace_settings.name = "Non-Color"
        sep = nt.nodes.new("ShaderNodeSeparateColor")
        nt.links.new(t.outputs["Color"], sep.inputs[0])
        nt.links.new(sep.outputs[0], g.inputs["Occlusion"])
    if alpha:
        mat.surface_render_method = "DITHERED"
    return mat


def _gltf_output_group():
    g = bpy.data.node_groups.get("glTF Material Output")
    if g:
        return g
    g = bpy.data.node_groups.new("glTF Material Output", "ShaderNodeTree")
    g.interface.new_socket("Occlusion", in_out="INPUT", socket_type="NodeSocketFloat")
    g.interface.new_socket("Thickness", in_out="INPUT", socket_type="NodeSocketFloat")
    return g


def assign_single_material(obj, mat):
    obj.data.materials.clear()
    obj.data.materials.append(mat)
    for p in obj.data.polygons:
        p.material_index = 0


def apply_modifier(obj, mod):
    for o in bpy.context.selected_objects:
        o.select_set(False)
    bpy.context.view_layer.objects.active = obj
    obj.select_set(True)
    bpy.ops.object.modifier_apply(modifier=mod.name)


def decimate(obj, ratio, keep_shapes=True):
    """Collapse-decimate a mesh; shape keys survive as interpolated vector attributes and are rebuilt."""
    if ratio >= 0.999 or len(obj.data.polygons) < 50:
        return
    deltas = []
    sk = obj.data.shape_keys
    if sk is not None and keep_shapes:
        base = get_co(obj, sk.key_blocks[0])
        for kb in sk.key_blocks[1:]:
            name = "skd_%d" % len(deltas)
            a = obj.data.attributes.new(name, "FLOAT_VECTOR", "POINT")
            a.data.foreach_set("vector", (get_co(obj, kb) - base).ravel())
            deltas.append((kb.name, name))
    if sk is not None:
        obj.shape_key_clear()
    mod = obj.modifiers.new("Decimate", "DECIMATE")
    mod.decimate_type = "COLLAPSE"
    mod.ratio = ratio
    for o in bpy.context.selected_objects:
        o.select_set(False)
    bpy.context.view_layer.objects.active = obj
    obj.select_set(True)
    bpy.ops.object.modifier_move_to_index(modifier=mod.name, index=0)
    apply_modifier(obj, mod)
    if deltas:
        co = get_co(obj)
        ensure_basis(obj)
        n = len(obj.data.vertices)
        for kname, aname in deltas:
            a = np.empty(n * 3, dtype=np.float32)
            obj.data.attributes[aname].data.foreach_get("vector", a)
            add_shape(obj, kname, co + a.reshape(n, 3))
            obj.data.attributes.remove(obj.data.attributes[aname])
